record_data = [
    # adding wins and losses data to the players who already got calculated to win MVP for display purposes 
    { 'team': 'Chiefs', 'year': '2018', 'wins': 12, 'losses': 4 },
    { 'team': 'Ravens', 'year': '2019', 'wins': 14, 'losses': 2 },
    { 'team': 'Packers', 'year': '2020', 'wins': 13, 'losses': 3 },
    { 'team': 'Buccaneers', 'year': '2021', 'wins': 13, 'losses': 4 },
    # 2022 Records
    { 'team': 'Chiefs', 'year': '2022', 'wins': 14, 'losses': 3 },
    { 'team': 'Eagles', 'year': '2022', 'wins': 14, 'losses': 3 },
    { 'team': 'Bills', 'year': '2022', 'wins': 13, 'losses': 3 },
    { 'team': '49ers', 'year': '2022', 'wins': 13, 'losses': 4 },
    { 'team': 'Bengals', 'year': '2022', 'wins': 12, 'losses': 4 },
    { 'team': 'Cowboys', 'year': '2022', 'wins': 12, 'losses': 5 },
    { 'team': 'Ravens', 'year': '2022', 'wins': 10, 'losses': 7 },
    { 'team': 'Dolphins', 'year': '2022', 'wins': 9, 'losses': 8 },
    { 'team': 'Packers', 'year': '2022', 'wins': 8, 'losses': 9 },
    { 'team': 'Vikings', 'year': '2022', 'wins': 13, 'losses': 4 },
    { 'team': 'Giants', 'year': '2022', 'wins': 9, 'losses': 7, 'ties': 1 },
    { 'team': 'Jaguars', 'year': '2022', 'wins': 9, 'losses': 8 },
    { 'team': 'Seahawks', 'year': '2022', 'wins': 9, 'losses': 8 },
    { 'team': 'Chargers', 'year': '2022', 'wins': 10, 'losses': 7 },
    { 'team': 'Buccaneers', 'year': '2022', 'wins': 8, 'losses': 9 },
    { 'team': 'Titans', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Raiders', 'year': '2022', 'wins': 6, 'losses': 11 },
    { 'team': 'Falcons', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Saints', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Panthers', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Cardinals', 'year': '2022', 'wins': 4, 'losses': 13 },
    { 'team': 'Lions', 'year': '2022', 'wins': 9, 'losses': 8 },
    { 'team': 'Bears', 'year': '2022', 'wins': 3, 'losses': 14 },
    { 'team': 'Texans', 'year': '2022', 'wins': 3, 'losses': 13, 'ties': 1 },
    { 'team': 'Colts', 'year': '2022', 'wins': 4, 'losses': 12, 'ties': 1 },
    { 'team': 'Steelers', 'year': '2022', 'wins': 9, 'losses': 8 },
    { 'team': 'Broncos', 'year': '2022', 'wins': 5, 'losses': 12 },
    { 'team': 'Jets', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Commanders', 'year': '2022', 'wins': 8, 'losses': 8, 'ties': 1 },
    { 'team': 'Patriots', 'year': '2022', 'wins': 8, 'losses': 9 },
    { 'team': 'Browns', 'year': '2022', 'wins': 7, 'losses': 10 },
    { 'team': 'Rams', 'year': '2022', 'wins': 5, 'losses': 12 },

    # 2023 Records
    { 'team': 'Chiefs', 'year': '2023', 'wins': 11, 'losses': 6 },
    { 'team': 'Eagles', 'year': '2023', 'wins': 11, 'losses': 6 },
    { 'team': 'Bills', 'year': '2023', 'wins': 11, 'losses': 6 },
    { 'team': '49ers', 'year': '2023', 'wins': 12, 'losses': 5 },
    { 'team': 'Bengals', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Cowboys', 'year': '2023', 'wins': 12, 'losses': 5 },
    { 'team': 'Ravens', 'year': '2023', 'wins': 13, 'losses': 4 },
    { 'team': 'Dolphins', 'year': '2023', 'wins': 11, 'losses': 6 },
    { 'team': 'Packers', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Vikings', 'year': '2023', 'wins': 7, 'losses': 10 },
    { 'team': 'Giants', 'year': '2023', 'wins': 6, 'losses': 11},
    { 'team': 'Jaguars', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Seahawks', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Chargers', 'year': '2023', 'wins': 5, 'losses': 12 },
    { 'team': 'Buccaneers', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Titans', 'year': '2023', 'wins': 6, 'losses': 11 },
    { 'team': 'Raiders', 'year': '2023', 'wins': 8, 'losses': 9 },
    { 'team': 'Falcons', 'year': '2023', 'wins': 7, 'losses': 10 },
    { 'team': 'Saints', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Panthers', 'year': '2023', 'wins': 2, 'losses': 15 },
    { 'team': 'Cardinals', 'year': '2023', 'wins': 4, 'losses': 13 },
    { 'team': 'Lions', 'year': '2023', 'wins': 12, 'losses': 5 },
    { 'team': 'Bears', 'year': '2023', 'wins': 7, 'losses': 10 },
    { 'team': 'Texans', 'year': '2023', 'wins': 10, 'losses': 7 },
    { 'team': 'Colts', 'year': '2023', 'wins': 9, 'losses': 8 },
    { 'team': 'Steelers', 'year': '2023', 'wins': 10, 'losses': 7 },
    { 'team': 'Broncos', 'year': '2023', 'wins': 8, 'losses': 9 },
    { 'team': 'Jets', 'year': '2023', 'wins': 7, 'losses': 10 },
    { 'team': 'Commanders', 'year': '2023', 'wins': 4, 'losses': 13 },
    { 'team': 'Patriots', 'year': '2023', 'wins': 4, 'losses': 13 },
    { 'team': 'Browns', 'year': '2023', 'wins': 11, 'losses': 6 },
    { 'team': 'Rams', 'year': '2023', 'wins': 10, 'losses': 7 },

    # 2024 Records
    { 'team': 'Chiefs', 'year': '2024', 'wins': 15, 'losses': 2 },
    { 'team': 'Eagles', 'year': '2024', 'wins': 14, 'losses': 3 },
    { 'team': 'Bills', 'year': '2024', 'wins': 13, 'losses': 4 },
    { 'team': '49ers', 'year': '2024', 'wins': 6, 'losses': 11 },
    { 'team': 'Bengals', 'year': '2024', 'wins': 9, 'losses': 8 },
    { 'team': 'Cowboys', 'year': '2024', 'wins': 7, 'losses': 10 },
    { 'team': 'Ravens', 'year': '2024', 'wins': 12, 'losses': 5 },
    { 'team': 'Dolphins', 'year': '2024', 'wins': 8, 'losses': 9 },
    { 'team': 'Packers', 'year': '2024', 'wins': 11, 'losses': 6 },
    { 'team': 'Vikings', 'year': '2024', 'wins': 14, 'losses': 3 },
    { 'team': 'Giants', 'year': '2024', 'wins': 3, 'losses': 14},
    { 'team': 'Jaguars', 'year': '2024', 'wins': 4, 'losses': 13 },
    { 'team': 'Seahawks', 'year': '2024', 'wins': 10, 'losses': 7 },
    { 'team': 'Chargers', 'year': '2024', 'wins': 11, 'losses': 6 },
    { 'team': 'Buccaneers', 'year': '2024', 'wins': 10, 'losses': 7 },
    { 'team': 'Titans', 'year': '2024', 'wins': 3, 'losses': 14 },
    { 'team': 'Raiders', 'year': '2024', 'wins': 4, 'losses': 13 },
    { 'team': 'Falcons', 'year': '2024', 'wins': 8, 'losses': 9 },
    { 'team': 'Saints', 'year': '2024', 'wins': 5, 'losses': 12 },
    { 'team': 'Panthers', 'year': '2024', 'wins': 5, 'losses': 12 },
    { 'team': 'Cardinals', 'year': '2024', 'wins': 8, 'losses': 9 },
    { 'team': 'Lions', 'year': '2024', 'wins': 15, 'losses': 2 },
    { 'team': 'Bears', 'year': '2024', 'wins': 5, 'losses': 12 },
    { 'team': 'Texans', 'year': '2024', 'wins': 10, 'losses': 7 },
    { 'team': 'Colts', 'year': '2024', 'wins': 8, 'losses': 9 },
    { 'team': 'Steelers', 'year': '2024', 'wins': 10, 'losses': 7 },
    { 'team': 'Broncos', 'year': '2024', 'wins': 10, 'losses': 7 },
    { 'team': 'Jets', 'year': '2024', 'wins': 5, 'losses': 12 },
    { 'team': 'Commanders', 'year': '2024', 'wins': 12, 'losses': 5 },
    { 'team': 'Patriots', 'year': '2024', 'wins': 4, 'losses': 13 },
    { 'team': 'Browns', 'year': '2024', 'wins': 3, 'losses': 14 },
    { 'team': 'Rams', 'year': '2024', 'wins': 10, 'losses': 7 },
]

for record in record_data:
    record['year'] = int(record['year'])